### ISSUE TITLE
Expansion fails when <tab> has a mapping

### ISSUE THREAD

**Issue by kennykaye** [rstacruz/vim-hyperstyle#8]
When expanding something like `dib`, the expansion fails with the following error message:

```
Error detected while processing function hyperstyle#expand_space[1]..<SNR>278_expand_inline[6]..<SNR>278_expand[4]..<SNR>278_pyeval[1]..provider#python#Call:
line   18:
error caught in request handler 'python_eval ('(hyperstyle.expand_property("dibpumvisible() ? "\\hover"", True)) or ""',)':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/neovim/plugin/script_host.py", line 150, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1
    (hyperstyle.expand_property("dibpumvisible() ? "\hover"", True)) or ""
                                                                         ^
```

This is running:
neovim - NVIM 0.1.7
python - Python 3.6.0

**Comment by rstacruz** [comment]
Are you on OSX? Can you try this?

```vim
let g:python2_host_prog = '/usr/local/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'
```

**Comment by rstacruz** [comment]
> python - Python 3.6.0

It seems to be using python2.7 according to that stack trace. Not sure what's up though, it should be okay with either 2 or 3.

**Comment by kennykaye** [comment]
@rstacruz Thanks for the prompt response! Both host_progs are set. I'm running OSX 10.12.3

`echo has("python") && has("python3")` evaluates to `1`

**Comment by kennykaye** [comment]
Ok, interesting. I think I've found the conflict. The following line was present in my configuration and used for tab expansion with deoplete. When this is removed, the expansion works correctly. Is this the expected behavior?

```
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
```

**Comment by rstacruz** [comment]
Oh man, this is a tough problem to solve: multiple plugins that all work with `<tab>`.  what happened here is that Hyperstyle tries to account for old `<Tab>` mappings (such as yours) but doesn't know how to handle `<Expr>` mappings.

At the moment I have no idea how this can be worked around aside from removing that mapping :( If anyone more knowledgeable with Vim can chime in, it's [s:map_key in plugin/hyperstyle.vim](https://github.com/rstacruz/vim-hyperstyle/blob/master/plugin/hyperstyle.vim#L30-L40) that takes care of this.
